const newProducts = [
    {
        imageSource:require("../../assets/products/woman1.png"),
        bonusRate:0.2,
        rating:8,
        sellerName:"Dorothy Perkins",
        productName:"Yellow Dress",
        price:15,
    },
    {
        imageSource:require("../../assets/products/woman2.png"),
        bonusRate:0.3,
        rating:6,
        sellerName:"Dani",
        productName:"Purple Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/woman3.png"),
        bonusRate:0.3,
        rating:6,
        sellerName:"Dani Rova",
        productName:"Yellow Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/woman4.png"),
        bonusRate:0.1,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/woman5.png"),
        bonusRate:0.45,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/woman6.png"),
        bonusRate:0.11,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/woman7.png"),
        bonusRate:0.03,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/woman8.png"),
        bonusRate:0.05,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
]

const saleProducts = [
    {
        imageSource:require("../../assets/products/man8.png"),
        bonusRate:0.05,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/man7.png"),
        bonusRate:0.05,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/man6.png"),
        bonusRate:0.05,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/man5.png"),
        bonusRate:0.05,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/man4.png"),
        bonusRate:0.05,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/man3.png"),
        bonusRate:0.05,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/man2.png"),
        bonusRate:0.05,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
    {
        imageSource:require("../../assets/products/man1.png"),
        bonusRate:0.05,
        rating:9,
        sellerName:"Dani Rovana",
        productName:"Red Dress",
        price:34,
    },
]

export  {newProducts, saleProducts}